### ISSUE TITLE
Is this is the same version that's in pypi?

### ISSUE THREAD

**Issue by envisean** [joshgeller/PyPardot#5]

**Comment by fr-anthony** [comment]
More precisely, the released PyPI version does not appear to work against at least the prospect API - all of the requests I tried (`{read,upsert,delete,create}_by_email`) return error code 2, "invalid action".

The current `master` works fine.

**Comment by joshgeller** [comment]
Sorry guys, pypi isn't update to date.

**Comment by fr-anthony** [comment]
We've worked around this locally by hosting our own PyPI.

**Comment by fr-anthony** [comment]
Was there any public-facing resolution to this?

**Comment by joshgeller** [comment]
I will update pypi this weekend - as for project maintenance in general, I no longer work with Pardot nor do I have access to a functioning account, so it would be nice if someone else took over development. Otherwise this project will no longer be maintained by me.
