### ISSUE TITLE
Invalid Syntax error upon attempt to authenticate with Pardot

### ISSUE THREAD

**Issue by kghu** [joshgeller/PyPardot#6]
Dear JoshGeller / PyPardot maintainers,

I installed PyPardot, but the instant I try to authenticate with it, I get an error.

I have only the following 2 lines so far:

    from pypardot.client import PardotAPI
    p = PardotAPI(email='myemail@example.com', password='mypassword', user_key='myuserkey')

As soon as I try to execute this script, I get the following error _(I get it even with "p.authenticate()" as the next line of code - the code above is what I stripped things down to to isolate the problem)_:

    runfile('C:/path/myscript.py', wdir='C:/path')
      File "C:\mypythoninstallpath\lib\site-packages\pypardot\client.py", line 54
        except PardotAPIError, err:
                             ^
    SyntaxError: invalid syntax

Any ideas what's wrong?  Thank you!

**Comment by joshgeller** [comment]
I believe this is an Python 3 issue...unfortunately this module doesn't support Python 3 :(

However it would not be hard to port. Just a few `print` and `except` statements to update if anyone wants to take a shot at it. PRs are welcome.
